uint a = 8;
uint b = 2;
Console.WriteLine("Unary operations with uint");
Console.WriteLine(++a);
Console.WriteLine(--b);
Console.WriteLine("Binary operations with uint");
Console.WriteLine(a + b);
Console.WriteLine(a - b);
Console.WriteLine(a * b);
Console.WriteLine(a / b);
Console.WriteLine(a % b);
Console.WriteLine("Ternary operation with uint");
Console.WriteLine(a > b ? a + b : a - b);